### ISSUE TITLE
SIT742: Session 11B - Designing a Machine Learning System

### ISSUE THREAD

**Issue by Prabhmit** [tulip-lab/sit742#59]
Hello SIT742 teaching unit, this is a very good excercise and  provides a very useful framework for future projects. Thank you for that. 

Grateful if you can inspect/advise if step 1.2 is accurate.
I note that at step 1.2, the data is pre-processed first and then split into text and train. My understanding is that splitting needs to happen first followed by any processing as in real world, the test data is unseen.  Any pre-processing prior to split will lead to information about test set made avaible to the model and lead to exaggerated model metrics.  

Ref:
https://machinelearningmastery.com/data-preparation-without-data-leakage/

Regards

Prabhmit

**Comment by tuliplab** [comment]
For many application scenarios, it is necessary to pre-process the data prior to split the data into training/test.

For example, for normalization of a feature, such as "height", it is done on both training/testing dataset; 

Or for discretization of a feature, such as "age", from age into "junior, mature, senior" or others, it is needed to be done on all data, rather than later on on the test data only.
